# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."calibre" = {
    image = "ghcr.io/linuxserver/calibre";
    environment = {
      "CLI_ARGS" = "";
      "PGID" = "1001";
      "PUID" = "1000";
      "TZ" = "america/New_York";
      "UMASK_SET" = "022";
    };
    volumes = [
      "/HD:/HD:rw"
      "/HD/HD2/Config/calibre/config:/config:rw"
    ];
    ports = [
      "192.168.1.3:8050:8080/tcp"
      "192.168.1.3:8051:8081/tcp"
      "192.168.1.3:9050:9090/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=calibre"
      "--network=calibre_default"
    ];
  };
  systemd.services."docker-calibre" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-calibre_default.service"
    ];
    requires = [
      "docker-network-calibre_default.service"
    ];
    partOf = [
      "docker-compose-calibre-root.target"
    ];
    wantedBy = [
      "docker-compose-calibre-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-calibre_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f calibre_default";
    };
    script = ''
      docker network inspect calibre_default || docker network create calibre_default
    '';
    partOf = [ "docker-compose-calibre-root.target" ];
    wantedBy = [ "docker-compose-calibre-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-calibre-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
